// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: isuxportal/misc/bot/support.proto

package bot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportCommInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage *SupportCommInfo_Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *SupportCommInfo) Reset() {
	*x = SupportCommInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_misc_bot_support_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportCommInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportCommInfo) ProtoMessage() {}

func (x *SupportCommInfo) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_misc_bot_support_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportCommInfo.ProtoReflect.Descriptor instead.
func (*SupportCommInfo) Descriptor() ([]byte, []int) {
	return file_isuxportal_misc_bot_support_proto_rawDescGZIP(), []int{0}
}

func (x *SupportCommInfo) GetUsage() *SupportCommInfo_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type SupportCommInfo_Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageIdSince  uint64 `protobuf:"varint,1,opt,name=message_id_since,json=messageIdSince,proto3" json:"message_id_since,omitempty"`
	TeamId          int64  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClarificationId int64  `protobuf:"varint,3,opt,name=clarification_id,json=clarificationId,proto3" json:"clarification_id,omitempty"`
}

func (x *SupportCommInfo_Usage) Reset() {
	*x = SupportCommInfo_Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_misc_bot_support_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportCommInfo_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportCommInfo_Usage) ProtoMessage() {}

func (x *SupportCommInfo_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_misc_bot_support_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportCommInfo_Usage.ProtoReflect.Descriptor instead.
func (*SupportCommInfo_Usage) Descriptor() ([]byte, []int) {
	return file_isuxportal_misc_bot_support_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SupportCommInfo_Usage) GetMessageIdSince() uint64 {
	if x != nil {
		return x.MessageIdSince
	}
	return 0
}

func (x *SupportCommInfo_Usage) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SupportCommInfo_Usage) GetClarificationId() int64 {
	if x != nil {
		return x.ClarificationId
	}
	return 0
}

var File_isuxportal_misc_bot_support_proto protoreflect.FileDescriptor

var file_isuxportal_misc_bot_support_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x73,
	0x63, 0x2f, 0x62, 0x6f, 0x74, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x62, 0x6f, 0x74, 0x22, 0xd0,
	0x01, 0x0a, 0x0f, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x46, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x75, 0x0a, 0x05, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0f, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x31, 0x32, 0x2d,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x6f, 0x2f,
	0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2f,
	0x62, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isuxportal_misc_bot_support_proto_rawDescOnce sync.Once
	file_isuxportal_misc_bot_support_proto_rawDescData = file_isuxportal_misc_bot_support_proto_rawDesc
)

func file_isuxportal_misc_bot_support_proto_rawDescGZIP() []byte {
	file_isuxportal_misc_bot_support_proto_rawDescOnce.Do(func() {
		file_isuxportal_misc_bot_support_proto_rawDescData = protoimpl.X.CompressGZIP(file_isuxportal_misc_bot_support_proto_rawDescData)
	})
	return file_isuxportal_misc_bot_support_proto_rawDescData
}

var file_isuxportal_misc_bot_support_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_isuxportal_misc_bot_support_proto_goTypes = []interface{}{
	(*SupportCommInfo)(nil),       // 0: isuxportal.proto.misc.bot.SupportCommInfo
	(*SupportCommInfo_Usage)(nil), // 1: isuxportal.proto.misc.bot.SupportCommInfo.Usage
}
var file_isuxportal_misc_bot_support_proto_depIdxs = []int32{
	1, // 0: isuxportal.proto.misc.bot.SupportCommInfo.usage:type_name -> isuxportal.proto.misc.bot.SupportCommInfo.Usage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_isuxportal_misc_bot_support_proto_init() }
func file_isuxportal_misc_bot_support_proto_init() {
	if File_isuxportal_misc_bot_support_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_isuxportal_misc_bot_support_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportCommInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_misc_bot_support_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportCommInfo_Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isuxportal_misc_bot_support_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isuxportal_misc_bot_support_proto_goTypes,
		DependencyIndexes: file_isuxportal_misc_bot_support_proto_depIdxs,
		MessageInfos:      file_isuxportal_misc_bot_support_proto_msgTypes,
	}.Build()
	File_isuxportal_misc_bot_support_proto = out.File
	file_isuxportal_misc_bot_support_proto_rawDesc = nil
	file_isuxportal_misc_bot_support_proto_goTypes = nil
	file_isuxportal_misc_bot_support_proto_depIdxs = nil
}
