// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: isuxportal/resources/contestant_instance.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContestantInstance_Status int32

const (
	ContestantInstance_UNKNOWN    ContestantInstance_Status = 0
	ContestantInstance_PENDING    ContestantInstance_Status = 1
	ContestantInstance_MODIFYING  ContestantInstance_Status = 2
	ContestantInstance_STOPPED    ContestantInstance_Status = 3
	ContestantInstance_RUNNING    ContestantInstance_Status = 4
	ContestantInstance_TERMINATED ContestantInstance_Status = 5
)

// Enum value maps for ContestantInstance_Status.
var (
	ContestantInstance_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "MODIFYING",
		3: "STOPPED",
		4: "RUNNING",
		5: "TERMINATED",
	}
	ContestantInstance_Status_value = map[string]int32{
		"UNKNOWN":    0,
		"PENDING":    1,
		"MODIFYING":  2,
		"STOPPED":    3,
		"RUNNING":    4,
		"TERMINATED": 5,
	}
)

func (x ContestantInstance_Status) Enum() *ContestantInstance_Status {
	p := new(ContestantInstance_Status)
	*p = x
	return p
}

func (x ContestantInstance_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContestantInstance_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_isuxportal_resources_contestant_instance_proto_enumTypes[0].Descriptor()
}

func (ContestantInstance_Status) Type() protoreflect.EnumType {
	return &file_isuxportal_resources_contestant_instance_proto_enumTypes[0]
}

func (x ContestantInstance_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContestantInstance_Status.Descriptor instead.
func (ContestantInstance_Status) EnumDescriptor() ([]byte, []int) {
	return file_isuxportal_resources_contestant_instance_proto_rawDescGZIP(), []int{0, 0}
}

type ContestantInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64                     `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	CloudId            string                    `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	TeamId             int64                     `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Number             int64                     `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	PublicIpv4Address  string                    `protobuf:"bytes,4,opt,name=public_ipv4_address,json=publicIpv4Address,proto3" json:"public_ipv4_address,omitempty"`
	PrivateIpv4Address string                    `protobuf:"bytes,5,opt,name=private_ipv4_address,json=privateIpv4Address,proto3" json:"private_ipv4_address,omitempty"`
	Status             ContestantInstance_Status `protobuf:"varint,6,opt,name=status,proto3,enum=isuxportal.proto.resources.ContestantInstance_Status" json:"status,omitempty"`
	Team               *Team                     `protobuf:"bytes,16,opt,name=team,proto3" json:"team,omitempty"`
}

func (x *ContestantInstance) Reset() {
	*x = ContestantInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_resources_contestant_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContestantInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestantInstance) ProtoMessage() {}

func (x *ContestantInstance) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_resources_contestant_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestantInstance.ProtoReflect.Descriptor instead.
func (*ContestantInstance) Descriptor() ([]byte, []int) {
	return file_isuxportal_resources_contestant_instance_proto_rawDescGZIP(), []int{0}
}

func (x *ContestantInstance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContestantInstance) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *ContestantInstance) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ContestantInstance) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ContestantInstance) GetPublicIpv4Address() string {
	if x != nil {
		return x.PublicIpv4Address
	}
	return ""
}

func (x *ContestantInstance) GetPrivateIpv4Address() string {
	if x != nil {
		return x.PrivateIpv4Address
	}
	return ""
}

func (x *ContestantInstance) GetStatus() ContestantInstance_Status {
	if x != nil {
		return x.Status
	}
	return ContestantInstance_UNKNOWN
}

func (x *ContestantInstance) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

var File_isuxportal_resources_contestant_instance_proto protoreflect.FileDescriptor

var file_isuxportal_resources_contestant_instance_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x69, 0x73,
	0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x03,
	0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x2e, 0x0a, 0x13, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x70, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x30, 0x0a, 0x14, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x70, 0x76, 0x34,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x70, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x4d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x35, 0x2e, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x22, 0x5b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x4f, 0x44, 0x49, 0x46, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54,
	0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x05, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e,
	0x31, 0x32, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x67, 0x6f, 0x2f, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isuxportal_resources_contestant_instance_proto_rawDescOnce sync.Once
	file_isuxportal_resources_contestant_instance_proto_rawDescData = file_isuxportal_resources_contestant_instance_proto_rawDesc
)

func file_isuxportal_resources_contestant_instance_proto_rawDescGZIP() []byte {
	file_isuxportal_resources_contestant_instance_proto_rawDescOnce.Do(func() {
		file_isuxportal_resources_contestant_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_isuxportal_resources_contestant_instance_proto_rawDescData)
	})
	return file_isuxportal_resources_contestant_instance_proto_rawDescData
}

var file_isuxportal_resources_contestant_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_isuxportal_resources_contestant_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_isuxportal_resources_contestant_instance_proto_goTypes = []interface{}{
	(ContestantInstance_Status)(0), // 0: isuxportal.proto.resources.ContestantInstance.Status
	(*ContestantInstance)(nil),     // 1: isuxportal.proto.resources.ContestantInstance
	(*Team)(nil),                   // 2: isuxportal.proto.resources.Team
}
var file_isuxportal_resources_contestant_instance_proto_depIdxs = []int32{
	0, // 0: isuxportal.proto.resources.ContestantInstance.status:type_name -> isuxportal.proto.resources.ContestantInstance.Status
	2, // 1: isuxportal.proto.resources.ContestantInstance.team:type_name -> isuxportal.proto.resources.Team
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_isuxportal_resources_contestant_instance_proto_init() }
func file_isuxportal_resources_contestant_instance_proto_init() {
	if File_isuxportal_resources_contestant_instance_proto != nil {
		return
	}
	file_isuxportal_resources_team_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_isuxportal_resources_contestant_instance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContestantInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isuxportal_resources_contestant_instance_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isuxportal_resources_contestant_instance_proto_goTypes,
		DependencyIndexes: file_isuxportal_resources_contestant_instance_proto_depIdxs,
		EnumInfos:         file_isuxportal_resources_contestant_instance_proto_enumTypes,
		MessageInfos:      file_isuxportal_resources_contestant_instance_proto_msgTypes,
	}.Build()
	File_isuxportal_resources_contestant_instance_proto = out.File
	file_isuxportal_resources_contestant_instance_proto_rawDesc = nil
	file_isuxportal_resources_contestant_instance_proto_goTypes = nil
	file_isuxportal_resources_contestant_instance_proto_depIdxs = nil
}
