# frozen_string_literal: true

source "https://rubygems.org"

gem 'jwt'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'

group :development do
  gem 'irb'
end
