// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: isuxportal/services/admin/cloud_formation.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCloudFormationQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // query parameter. "test" | "qualify"
}

func (x *GetCloudFormationQuery) Reset() {
	*x = GetCloudFormationQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_admin_cloud_formation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCloudFormationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudFormationQuery) ProtoMessage() {}

func (x *GetCloudFormationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_admin_cloud_formation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudFormationQuery.ProtoReflect.Descriptor instead.
func (*GetCloudFormationQuery) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_admin_cloud_formation_proto_rawDescGZIP(), []int{0}
}

func (x *GetCloudFormationQuery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCloudFormationQuery) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetCloudFormationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template string `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
}

func (x *GetCloudFormationResponse) Reset() {
	*x = GetCloudFormationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_admin_cloud_formation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCloudFormationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudFormationResponse) ProtoMessage() {}

func (x *GetCloudFormationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_admin_cloud_formation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudFormationResponse.ProtoReflect.Descriptor instead.
func (*GetCloudFormationResponse) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_admin_cloud_formation_proto_rawDescGZIP(), []int{1}
}

func (x *GetCloudFormationResponse) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

var File_isuxportal_services_admin_cloud_formation_proto protoreflect.FileDescriptor

var file_isuxportal_services_admin_cloud_formation_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1f, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x22, 0x3c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x37, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x2f, 0x69,
	0x73, 0x75, 0x63, 0x6f, 0x6e, 0x31, 0x32, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x6f, 0x2f, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isuxportal_services_admin_cloud_formation_proto_rawDescOnce sync.Once
	file_isuxportal_services_admin_cloud_formation_proto_rawDescData = file_isuxportal_services_admin_cloud_formation_proto_rawDesc
)

func file_isuxportal_services_admin_cloud_formation_proto_rawDescGZIP() []byte {
	file_isuxportal_services_admin_cloud_formation_proto_rawDescOnce.Do(func() {
		file_isuxportal_services_admin_cloud_formation_proto_rawDescData = protoimpl.X.CompressGZIP(file_isuxportal_services_admin_cloud_formation_proto_rawDescData)
	})
	return file_isuxportal_services_admin_cloud_formation_proto_rawDescData
}

var file_isuxportal_services_admin_cloud_formation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_isuxportal_services_admin_cloud_formation_proto_goTypes = []interface{}{
	(*GetCloudFormationQuery)(nil),    // 0: isuxportal.proto.services.admin.GetCloudFormationQuery
	(*GetCloudFormationResponse)(nil), // 1: isuxportal.proto.services.admin.GetCloudFormationResponse
}
var file_isuxportal_services_admin_cloud_formation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_isuxportal_services_admin_cloud_formation_proto_init() }
func file_isuxportal_services_admin_cloud_formation_proto_init() {
	if File_isuxportal_services_admin_cloud_formation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_isuxportal_services_admin_cloud_formation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCloudFormationQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_admin_cloud_formation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCloudFormationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isuxportal_services_admin_cloud_formation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isuxportal_services_admin_cloud_formation_proto_goTypes,
		DependencyIndexes: file_isuxportal_services_admin_cloud_formation_proto_depIdxs,
		MessageInfos:      file_isuxportal_services_admin_cloud_formation_proto_msgTypes,
	}.Build()
	File_isuxportal_services_admin_cloud_formation_proto = out.File
	file_isuxportal_services_admin_cloud_formation_proto_rawDesc = nil
	file_isuxportal_services_admin_cloud_formation_proto_goTypes = nil
	file_isuxportal_services_admin_cloud_formation_proto_depIdxs = nil
}
