// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: isuxportal/services/contestant/notifications.proto

package contestant

import (
	resources "github.com/isucon/isucon12-portal/proto.go/isuxportal/resources"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNotificationsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Last notifications.id that a user-agent has received through ListNotificationsQuery during a current session.
	// If not specified (=0), uses server-side `read` column as a hint.
	After int64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *ListNotificationsQuery) Reset() {
	*x = ListNotificationsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotificationsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsQuery) ProtoMessage() {}

func (x *ListNotificationsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsQuery.ProtoReflect.Descriptor instead.
func (*ListNotificationsQuery) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsQuery) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastAnsweredClarificationId int64                     `protobuf:"varint,1,opt,name=last_answered_clarification_id,json=lastAnsweredClarificationId,proto3" json:"last_answered_clarification_id,omitempty"`
	Notifications               []*resources.Notification `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsResponse) GetLastAnsweredClarificationId() int64 {
	if x != nil {
		return x.LastAnsweredClarificationId
	}
	return 0
}

func (x *ListNotificationsResponse) GetNotifications() []*resources.Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type SubscribeNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh   string `protobuf:"bytes,2,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth     string `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *SubscribeNotificationRequest) Reset() {
	*x = SubscribeNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNotificationRequest) ProtoMessage() {}

func (x *SubscribeNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNotificationRequest.ProtoReflect.Descriptor instead.
func (*SubscribeNotificationRequest) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeNotificationRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SubscribeNotificationRequest) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *SubscribeNotificationRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type SubscribeNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeNotificationResponse) Reset() {
	*x = SubscribeNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNotificationResponse) ProtoMessage() {}

func (x *SubscribeNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNotificationResponse.ProtoReflect.Descriptor instead.
func (*SubscribeNotificationResponse) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{3}
}

type UnsubscribeNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *UnsubscribeNotificationRequest) Reset() {
	*x = UnsubscribeNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeNotificationRequest) ProtoMessage() {}

func (x *UnsubscribeNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeNotificationRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeNotificationRequest) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeNotificationRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type UnsubscribeNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnsubscribeNotificationResponse) Reset() {
	*x = UnsubscribeNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeNotificationResponse) ProtoMessage() {}

func (x *UnsubscribeNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isuxportal_services_contestant_notifications_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeNotificationResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeNotificationResponse) Descriptor() ([]byte, []int) {
	return file_isuxportal_services_contestant_notifications_proto_rawDescGZIP(), []int{5}
}

var File_isuxportal_services_contestant_notifications_proto protoreflect.FileDescriptor

var file_isuxportal_services_contestant_notifications_proto_rawDesc = []byte{
	0x0a, 0x32, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x1a, 0x27, 0x69, 0x73, 0x75, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x66,
	0x74, 0x65, 0x72, 0x22, 0xb0, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x1e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x65, 0x64, 0x5f, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1b, 0x6c, 0x61, 0x73, 0x74, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x61, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x4e, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x66, 0x0a, 0x1c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x32, 0x35, 0x36, 0x64, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x32, 0x35, 0x36, 0x64, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x1f,
	0x0a, 0x1d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x3c, 0x0a, 0x1e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x21, 0x0a,
	0x1f, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x73, 0x75, 0x63, 0x6f, 0x6e, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x31, 0x32, 0x2d, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x6f, 0x2f, 0x69,
	0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isuxportal_services_contestant_notifications_proto_rawDescOnce sync.Once
	file_isuxportal_services_contestant_notifications_proto_rawDescData = file_isuxportal_services_contestant_notifications_proto_rawDesc
)

func file_isuxportal_services_contestant_notifications_proto_rawDescGZIP() []byte {
	file_isuxportal_services_contestant_notifications_proto_rawDescOnce.Do(func() {
		file_isuxportal_services_contestant_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_isuxportal_services_contestant_notifications_proto_rawDescData)
	})
	return file_isuxportal_services_contestant_notifications_proto_rawDescData
}

var file_isuxportal_services_contestant_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_isuxportal_services_contestant_notifications_proto_goTypes = []interface{}{
	(*ListNotificationsQuery)(nil),          // 0: isuxportal.proto.services.contestant.ListNotificationsQuery
	(*ListNotificationsResponse)(nil),       // 1: isuxportal.proto.services.contestant.ListNotificationsResponse
	(*SubscribeNotificationRequest)(nil),    // 2: isuxportal.proto.services.contestant.SubscribeNotificationRequest
	(*SubscribeNotificationResponse)(nil),   // 3: isuxportal.proto.services.contestant.SubscribeNotificationResponse
	(*UnsubscribeNotificationRequest)(nil),  // 4: isuxportal.proto.services.contestant.UnsubscribeNotificationRequest
	(*UnsubscribeNotificationResponse)(nil), // 5: isuxportal.proto.services.contestant.UnsubscribeNotificationResponse
	(*resources.Notification)(nil),          // 6: isuxportal.proto.resources.Notification
}
var file_isuxportal_services_contestant_notifications_proto_depIdxs = []int32{
	6, // 0: isuxportal.proto.services.contestant.ListNotificationsResponse.notifications:type_name -> isuxportal.proto.resources.Notification
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_isuxportal_services_contestant_notifications_proto_init() }
func file_isuxportal_services_contestant_notifications_proto_init() {
	if File_isuxportal_services_contestant_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_isuxportal_services_contestant_notifications_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotificationsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_contestant_notifications_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotificationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_contestant_notifications_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_contestant_notifications_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_contestant_notifications_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isuxportal_services_contestant_notifications_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isuxportal_services_contestant_notifications_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isuxportal_services_contestant_notifications_proto_goTypes,
		DependencyIndexes: file_isuxportal_services_contestant_notifications_proto_depIdxs,
		MessageInfos:      file_isuxportal_services_contestant_notifications_proto_msgTypes,
	}.Build()
	File_isuxportal_services_contestant_notifications_proto = out.File
	file_isuxportal_services_contestant_notifications_proto_rawDesc = nil
	file_isuxportal_services_contestant_notifications_proto_goTypes = nil
	file_isuxportal_services_contestant_notifications_proto_depIdxs = nil
}
