name: Bench Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.18
    name: Build
    runs-on: [self-hosted, core16, self-hosted-runner-2]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: "[bench] Get dependencies"
      working-directory: ./bench
      env:
        TZ: Asia/Tokyo
      run: |
        go get -v -t -d ./...
    - name: "[bench] Test"
      working-directory: ./bench
      env:
        TZ: Asia/Tokyo
      run: |
        go test -v ./...
