name: Sync to webapp diff branch for porting
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/go/isuports.go'
      - 'webapp/go/sqltrace.go'
      - 'webapp/go/cmd/isuports/main.go'
  workflow_dispatch:

jobs:
  sync:
    name: checkout
    runs-on: [self-hosted, core16, self-hosted-runner-2]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: checkout and push from main
      run: |
        git checkout do-not-merge/diff-webapp6
        git checkout main webapp/go/isuports.go webapp/go/sqltrace.go webapp/go/cmd/isuports/main.go
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m 'backport from main'
        git push origin do-not-merge/diff-webapp6
